### ISSUE TITLE
Curriculum Celeste

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [NataliaAlvarezIspc/GroupTSDWAD-ISPC#13]
Subir curriculum en formato pdf

**Comment by AhumadaCeleste** [comment]
Aquí comparto mi cv. formato pdf.

**Curriculum-vitae_Ahumada.Celeste.pdf**

**Comment by AhumadaCeleste** [comment]
ISPC/blob/e0dce31dff781b031f750ceb15999f25e68bff12/Curriculum-vitae_Ahumada.Celeste.pdf

**Comment by AhumadaCeleste** [comment]
[https://github.com/NataliaAlvarezIspc/GroupTSDWAD-ISPC/blob/e0dce31dff781b031f750ceb15999f25e68bff12/Curriculum-vitae_Ahumada.Celeste.pdf](url)
