### ISSUE TITLE
Ceremonias de Scrum

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [NataliaAlvarezIspc/GroupTSDWAD-ISPC#2]
#Redactar aquí las Ceremonias de Scrum

**Comment by CatalinaArtino66** [comment]
- Ceremonias

Las ceremonias de Scrum (a veces también llamadas “eventos Scrum”) son, por así decirlo, reuniones que tienen lugar en las iteraciones o Sprints contemplados dentro de la metodología Scrum, y son una parte importante del progreso de cualquier proyecto.
Estas ceremonias brindan un marco en el que los equipos pueden trabajar de manera más estructurada para que así se alcancen los resultados esperados. Sin embargo, si no se gestionan de la manera correcta, terminan abrumando y disminuyendo el valor que originalmente deberían proporcionar.
Ceremonias que se realizan a lo largo del proyecto:
● Sprint Planning Meeting
● Sprint Planning Meeting
● Daily Scrum Meeting
● Sprint Review Meeting
● Sprint Retrospective Meeting

● Sprint Planning Meeting (reunión de planificación del sprint). Se produce al iniciar cada
Sprint y tiene por objetivo decidir que se va a realizar en el Sprint.

● Daily Scrum Meeting (reunión periódica). Se produce diariamente, y tiene un máximo de
20 min. de duración. Tiene por objeto tratar qué es lo que se hizo, qué se va a hacer y
qué problemas se han encontrado, esto a fines de encontrar soluciones en la diaria.

● Sprint Review Meeting (reunión de revisión del Sprint). Se produce al finalizar el Sprint y
tiene por objeto mostrar qué es lo que se ha completado y qué no. Debe estar presente el
Product Owner.

● Sprint Retrospective Meeting (reunión de retrospectiva del Sprint). Se produce también al
finalizar el Sprint y tiene por objeto documentar qué ha funcionado y qué no ha funcionado
en el Sprint. La idea de dicha reunión es centrar al equipo en lo que salió bien y en lo que
debe mejorar para la próxima iteración. De ninguna manera se centra en lo que salió mal.
Planificación del Sprint
(Sprint Planning)
![image](https://user-images.githubusercontent.com/106894439/174916091-be3440d0-3642-4231-8c9d-9cec8155b0b8.png)
![image](https://user-images.githubusercontent.com/106894439/174916153-a673f8c2-4a52-4716-aad7-12d0857e65b2.png)
#No son reuniones de reporte de estado al scrum master
#Son compromisos frente  los demás miembros del equipo
![image](https://user-images.githubusercontent.com/106894439/174916903-b97fb1f6-b396-4cca-a56f-cd260ed9f617.png)
[](![image](https://user-images.githubusercontent.com/106894439/174916939-aa56e534-6df8-4523-b317-269af7dc8e68.png))

#A continuación una guía rápida y práctica de las 4 ceremonias de la metodología scrum:
https://thedigitalprojectmanager.com/es/ceremonias-scrum-simplificadas/
