### ISSUE TITLE
Scrum

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [NataliaAlvarezIspc/GroupTSDWAD-ISPC#4]
#Redactar aquí que es Srum

**Comment by asm3456** [comment]
SCRUM : Es un marco de trabajo atravez del cual las personas pueden abordar problemas complejos adaptativos,a la vez que se entregan productos de forma eficiente y creativa con el maximo valor.

**Comment by asm3456** [comment]
https//www.youtube.com/watch?v=a33xOe9d_Dk****
