### ISSUE TITLE
Metodologías Agiles y Gestión de Proyectos

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [NataliaAlvarezIspc/GroupTSDWAD-ISPC#6]

**Comment by IsmaelSena** [comment]
METODOLOGIA AGILES
SCRUM
Proceso para el desarrollo de software Define un conjunto completo de actividades que necesarias para concluir el objetivo.
MODELO CASCADA
1)	DEFINICION DE REQUERIMIENTOS
2)	DISEÑO DEL SOFTWARE Y DEL SISTEMA
3)	IMPLEMENTACION Y PRUEBAS DE UNIDADES
4)	INTEGRACION Y PRUEBA DE SISTEMAS
5)	OPERACIONES Y MANTENIMIENTO

CICLO DE VIDA
El ciclo de vida de un software corresponde desde el momento en que se da inicio al desarrollo del mismo, hasta que este deje de tener uso. El mismo consta de estándares para su creación, mantenimiento y explotación.
AGILIDAD
“La gestión de proyectos ágil no se formula sobre la necesidad de anticipación, sino sobre la adaptación continua.”
Quizá ya no hay “productos finales”, sino productos en continua evolución y mejora.
MANIFIESTO AGILE (VALORES)
-Valorar al individuo por encima de los procesos.
-El software que funciona por encima de la documentación exhaustiva.
-La colaboración del cliente por encima de lo contractual.
-La respuesta al cambio por encima del seguimiento de un plan.
-Colaboración estrecha con el cliente.
-Predisposición y respuesta al cambio.
-Desarrollo incremental con entregas frecuentes de funcionalidad.
-Comunicación verbal directa.
-Simplicidad, sólo los artefactos necesarios.
-Motivación, compromiso y responsabilidad del equipo por la autogestión, auto-organización.
DEFINICION SCRUM
Es un marco de trabajo a través del cual las personas pueden abordar problemas complejos adaptativos, a la vez que se entregan productos de forma eficiente y creativa con el máximo valor.
CARACTERISTICAS
*: Es un marco de trabajo a través del cual las personas pueden abordar problemas complejos adaptativos, a la vez que se entregan productos de forma eficiente y creativa con el máximo valor.
*Utiliza procesos interactivos/incrementales.
*Orientado a resultados y compromisos.
*No está restringido a proyectos de software solamente.
*Su visión es opuesta a la propuesta por la metodología en cascada.
PILARES
Transparencia Los aspectos significativos del proceso deben ser visibles para todos aquellos que son responsables del resultado. La transparencia requiere que dichos aspectos sean definidos en base a un estándar común, de tal modo que los observadores compartan un entendimiento común de lo que se están viendo. 
Inspección Los usuarios de Scrum deben inspeccionar frecuentemente los Artefactos de Scrum y el progreso hacia un objetivo para detectar variaciones indeseadas. Su inspección no debe ser tan frecuente como para que pueda interferir en el trabajo. Las inspecciones son más beneficiosas cuando se realizan de forma diligente por inspectores expertos en el mismo lugar de trabajo. 
Adaptación Si un inspector determina que uno o más aspectos de un proceso se desvían de los límites aceptables y que el producto resultante será inaceptable, el proceso o el material que está siendo procesado deben ajustarse
SPRINT
El Sprint es un período de corta duración que debe finalizar con un prototipo operativo o producto parcialmente entregable. El mismo se repite n veces a lo largo del proyecto y permite hacer entregas de producto en partes, donde cada entrega, es un incremento de funcionalidad respecto al anterior.
DURANTE EL SPRINT
*No se realizan cambios que puedan afectar al objetivo del Sprint (Sprint Goal);
*Los objetivos de calidad no disminuyen;
*El alcance puede clarificarse y renegociarse entre el Propietario del Producto (Product Owner) y el Equipo de Desarrollo a medida que se va aprendiendo más.
COMUNICACIÓN 
“La forma más eficiente y efectiva de comunicar información de ida y vuelta dentro de un equipo de desarrollo es mediante la comunicación cara a cara”
