### ISSUE TITLE
Etica y Deontologia

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [NataliaAlvarezIspc/GroupTSDWAD-ISPC#7]

**Comment by IngridAlcocer05** [comment]
ETICA Y DEONTOLOGIA

La ética abarca el conjunto de normas que hacen y mejoran el desarrollo de la actividad de los profesionales y es la encargada de ir marcando las pautas éticas del desarrollo de su actividad mediante valores universales reconocidos por cada persona.

Debido a que internet es una red de comunicación no regulada, permitiendo que algunos usuarios comenten actividades no éticas e ilegales que perjudican a la sociedad, la informática se ha visto en la necesidad de reflexionar sobre una ética particular, que fue determinada como ética informática (EI). Su origen esta en el uso cada ves mayor de las tecnologías de la información en nuestra vida social. Su rol deriva en analizar problemas éticos que son creados por la tecnología en el uso y manejo de ordenadores, como también los que son transformados o agravados por la misma.

La ética informática la podemos aplicar descubriendo y articulando dilemas éticos claves en informática, proponiendo un marco conceptual adecuado para entender dichos dilemas éticos originados por informática y estableciendo una guía que reglamente el uso de las tecnologías en la información. 

El objetivo de la EI es de aportar guías sobre la forma adecuada de actuación cuando no hay reglamentación. 

El contenido de ética en informática es importante, por ser considerarlo como un instrumento que facilita reconocer los problemas y resolverlos de acuerdo a los objetivos buscados. Los códigos de ética, tal como se conocen en el mundo de las empresas, son sistemas de reglas establecidos con el propósito general de guiar el comportamiento de los integrantes de la organización y de aquellos con los cuales ésta actúa habitualmente: clientes, proveedores y contratistas.

CODIGOS ETICOS:
La informática afecta a los derechos fundamentales que involucran la protección de copyright, la libertad intelectual, la contabilidad y la seguridad. Existen códigos profesionales que ofrecen una base para tomar decisiones éticas y aplicar soluciones éticas a situaciones que involucran la provisión y uso de información que reflejan la dedicación de una organización al servicio informático responsable. La evolución de los formatos y necesidades informáticos requiere reconsideración continua de los principios éticos y como se aplican estos códigos. Las consideraciones en cuanto a la infoetica influencian las decisiones personales, la practica profesional y la política publica. Por lo tanto, el análisis ético debe proveer una base para tomar en consideración muchos y varios dominios en cuanto a como se distribuye la información. 

LAS PROPIEDADES DE LOS BIENES INFORMATICOS:
El software informático es un bien que describe un conjunto de instrucciones que indican lo que un sistema informático debe hacer. Conforme el software va adquiriendo mas importancia en la sociedad, hay toda una serie de problemas que hay que tener en cuenta. El primer problema que aparece con el software es la copia ilegal de programas. Otra cuestión que aparece con el desarrollo del software es el problema de la calidad de una aplicación informática. Las aplicaciones informáticas complejas se realizan entre un equipo de personas que desarrollan tareas diversas tales como formalizar (especificar) el problema, programar el código de la aplicación, someterle a una batería de pruebas, realizar la instalación de la aplicación y por ultimo verificar su correcto funcionamiento. En el caso de aplicaciones complejas, es imposible que se lleguen a testear completamente, por lo que el comprador se tiene que conformar con que hay una alta probabilidad de que el programa no tenga ningún error. Son numerosos los problemas y no tienen una solución fácil.

**Comment by IngridAlcocer05** [comment]
**ÉTICA Y DEONTOLOGÍA PROFESIONAL

ÉTICA EN LA INFORMÁTICA**
La ética abarca el conjunto de normas que hacen y mejoran el desarrollo de la actividad de los profesionales y es la encargada de ir marcando las pautas éticas del desarrollo de su actividad mediante valores universales reconocidos por cada persona.
Debido a que internet es una red de comunicación no regulada, permitiendo que algunos usuarios comenten actividades no éticas e ilegales que perjudican a la sociedad, la informática se ha visto en la necesidad de reflexionar sobre una ética particular, que fue determinada como ética informática (EI). Su origen está en el uso cada vez mayor de las tecnologías de la información en nuestra vida social. Su rol deriva en analizar problemas éticos que son creados por la tecnología en el uso y manejo de ordenadores, como también los que son transformados o agravados por la misma.
La ética informática la podemos aplicar descubriendo y articulando dilemas éticos claves en informática, proponiendo un marco conceptual adecuado para entender dichos dilemas éticos originados por informática y estableciendo una guía que reglamente el uso de las tecnologías en la información.
El objetivo de la EI es de aportar guías sobre la forma adecuada de actuación cuando no hay reglamentación.
El contenido de ética informática es importante, por ser considerarlo como un instrumento que facilita reconocer los problemas y resolverlos de acuerdo a los objetivos buscados. Los códigos de ética, tal como se conocen en el mundo de las empresas, son sistemas de reglas establecidos con el propósito general de guiar el comportamiento de los integrantes de la organización y de aquellos con los cuales ésta actúa habitualmente: clientes, proveedores y contratistas.

A continuación se conceptualizan los principios que adopta la ética de la información:
**_- La uniformidad:_** todo se procesa, se tratan los funcionamientos, cambios, acciones y eventos como procesos de información, pero el proceso no será tomado como tal, sino se seleccionará lo más significativo de la actividad.
**_- La reflexividad de procesos de información:_** cualquier proceso de información necesariamente genera y es responsable de la información.
**_- La inevitabilidad de procesos de información:_** la ausencia de información también es un proceso de información.
**_- La uniformidad de ser:_** una entidad es un paquete consistente de información, que puede nombrarse y la ética trata cada entidad como una entidad de información.
**_- La uniformidad de agencia:_** un agente es cualquier entidad, capaz de definir fenómenos para la producción de información y que puede afectar la infoesfera. No todas las entidades de información son agentes.
**_- La uniformidad de no ser:_** no ser, es la ausencia o negación de cualquier información o lo que se denomina entropía de información, esta es una cantidad específica de desorden, degradación o aleatoriedad en un sistema de energía productiva de información, es el ruido.

**CÓDIGOS ÉTICOS:**
La informática afecta a los derechos fundamentales que involucran la protección de copyright, la libertad intelectual, la contabilidad y la seguridad. Existen códigos profesionales que ofrecen una base para tomar decisiones éticas y aplicar soluciones éticas a situaciones que involucran la provisión y uso de información que reflejan la dedicación de una organización al servicio informático responsable. La evolución de los formatos y necesidades informáticos requiere reconsideración continua de los principios éticos y cómo se aplican estos códigos. Las consideraciones en cuanto a la infoetica influencian las decisiones personales, la practica profesional y la política pública. Por lo tanto, el análisis ético debe proveer una base para tomar en consideración muchos y varios dominios en cuanto a cómo se distribuye la información.

**LAS PROPIEDADES DE LOS BIENES INFORMÁTICOS:**
El software informático es un bien que describe un conjunto de instrucciones que indican lo que un sistema informático debe hacer. Conforme el software va adquiriendo más importancia en la sociedad, hay toda una serie de problemas que hay que tener en cuenta. El primer problema que aparece con el software es la copia ilegal de programas. Otra cuestión que aparece con el desarrollo del software es el problema de la calidad de una aplicación informática. Las aplicaciones informáticas complejas se realizan entre un equipo de personas que desarrollan tareas diversas tales como formalizar (especificar) el problema, programar el código de la aplicación, someterle a una batería de pruebas, realizar la instalación de la aplicación y por último verificar su correcto funcionamiento. En el caso de aplicaciones complejas, es imposible que se lleguen a testear completamente, por lo que el comprador se tiene que conformar con que hay una alta probabilidad de que el programa no tenga ningún error, debido a estas situaciones son numerosos los problemas que se presentan.

**ETICA Y MORAL**
Ambos términos presentan una gran diferencia, tanto la ética y moral se ocupan de los actos humanos pero la ética los estudia para explicar cómo son estos actos, mientras que la moral indica cómo deben ser. En otras palabras, la ética describe y la moral prescribe. Es decir a diferencia de la ética, la moral tiende a la subjetividad y a la diversidad de interpretaciones, en cambio la ética al ser una ciencia objetiva y ser una rama de la filosofía, estudia la esencia y los juicios de la conducta humana en la sociedad, para proponer principios y normas regulativas que nos permitan a los individuos la formación de una sociedad creciente.

![Esta es una imagen] (https://user-images.githubusercontent.com/106851962/175194589-2927e940-ebb6-42e6-84c0-55b6ff40f90c.jpg)

**ÉTICA ETIMOLÓGICA** 
La definición de ética se basa en su raíz etimología, la cual es proveniente del latín êthos que hace alusión al carácter o lo perteneciente al carácter. Asimismo, la ética puede estar relacionada tanto a la parte social de la persona como a la ética profesional o la ética empresarial de un conjunto de trabajadores.

**ETIMOLOGÍA DE MORAL**
La moral es un conjunto de normas, creencias, valores y costumbres que dirigen o guían la conducta de grupos de personas en la sociedad. Se distingue de la ética en que esta es una moral transcultural o universal, aunque ambas se suelen confundir. La moral permite distinguir cuáles acciones son buenas y cuáles malas para un grupo social. Otra perspectiva la define como el conocimiento de lo que el ser humano debe hacer o evitar para conservar la estabilidad social.

**CODIGOS MORALES** 
Un código moral es un conjunto de normas y valores morales que garantizan la supervivencia del grupo a través de acuerdos entre lo que debe ser considerado moralmente bueno o malo. Los códigos morales se establecen entre un grupo de personas, sin importar el tipo y tamaño, puede tratarse de una familia, de un equipo, de una nación o de una comunidad. Dado que las personas pertenecemos a diferentes grupos sociales, regimos nuestra conducta en base a diferentes códigos morales. 

**DEONTOLOGIA INFORMATICA** 
La deontología es un sentido más amplio, la ciencia o tratado de los deberes y normas morales. En un sentido más concreto, tiene que ver con el comportamiento moral o ético, es decir con los principios y normas morales que regulan las actividades humanas. La deontología informática, por extensión, trata, por tanto, de la moral o ética profesional en el manejo del activo más importante que tienen las empresas, un bien cada vez más apreciado, que es la información.

**LA SOCIEDAD DE LA INFORMACIÓN** 
La Sociedad de la Información es un hecho permanentemente reconstruido por actores que pertenecen a sectores sociales de la gran mayoría de los países del globo. A través de la creación, distribución y manipulación de la información se vinculan con gran parte de las actividades culturales y económicas. 

Estas cuatro leyes clarifican las grandes líneas de cómo pueden vivir las personas, como agentes responsables en la Sociedad de la información o post-información. 
                   **-** Nunca se tiene que producir entropía «ausencia de información semántica» en la infoetica.
                   **-** Debe prevenirse la entropía en la infoetica.
                   **-** Se tiene que eliminar la entropía en la infoetica.
                   **-** Se debe garantizar el bienestar, la cantidad, calidad y variedad de la información en la infoetica.

La evolución acelerada de las TICs ha generado cambios en todos los ámbitos sociales, económicos y financieros; ha producido la aparición de una cultura informática que está perturbando directa o indirectamente los valores morales y éticos de los individuos y de las organizaciones. La atención de los actuales gerentes debe enfocarse en el desarrollo vertiginoso, constante y evidente de las TICs, y en el cambio que el desarrollo tecnológico está generando en esta sociedad actual. 

Los problemas en los sitios de trabajo informatizados, las aplicaciones de las leyes en el ciberespacio, la ética de la computadora profesional y la metodología de códigos profesionales son temas para el estudio de la ética. Surgen entonces problemas en los ambientes de trabajo, códigos de ética profesionales para los consumidores y profesionales de la informática, la ética de la inteligencia artificial y la vida artificial, los problemas éticos de la sociedad de la información son transformados profundamente por la tecnología de la información, esta no solo tiene un valor por el discurso moral y en nuestros conceptos éticos sino también en nuestras experiencias personales, nuestra identidad mental y física.

**DILEMAS EN LAS REDES SOCIALES**
Las redes sociales constituyen una gran plataforma de información disponible para todo el mundo y por ende dependiendo de las tendencias de los diferentes grupos y momentos que se viven, se pueden generar situaciones que propicien caos, discriminación, polarización, alineación y solo ser revertidos por motivaciones positivas como orden, altruismo, democracia, ayuda social y que se logrará siempre que la sociedad asuma su responsabilidad. Ahora bien, cada vez más, sabemos las problemáticas que hay detrás de las redes sociales. Este mundo virtual  ha estudiado perfectamente el comportamiento humano y los procesos psicológicos. Por ello, todo está preparado para generar una adicción y dependencia  a las redes sociales y a Internet.

Cómo influyen negativamente las redes sociales en la vida de las personas, mediante el funcionamiento de un modelo de negocios de las redes sociales como YouTube, Instagram o Facebook, y en base a la venta de publicidad es importante que las redes sociales capten la atención de las personas mientras más personas y más tiempo pasen viendo las redes más ganancias tendrá la empresa. Por eso las redes sociales pelean por la atención de los usuarios, buscan la manera de retener al usuario por más tiempo, lo cual sucede en que delimita el tiempo de las personas.

[El lado oscuro de las redes sociales] (https://www.youtube.com/watch?v=trGgBTbj4z8)
