### ISSUE TITLE
Inglés

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [NataliaAlvarezIspc/GroupTSDWAD-ISPC#8]

**Comment by NataliaAlvarezIspc** [comment]
**Hola como va?**

- sdjfjsdfsjsdfjsdk
- ldfjkdfskdfsd
- jlsdjfsdfdssklf

**Comment by RuthEKF** [comment]
**Material Bloque I**
1. Lectocomprensión en inglés

PRE-LECTURA: ANTICIPACIÓN las actividades de pre-lectura, que son las que permiten dotarse de objetivos de lectura y actualizar los conocimientos previos relevantes.
Previewing : la previsualización consiste en dar una mirada general, global al texto con el fin de determinar a grandes rasgos el tema del mismo.
Hipótesis de lectura: consiste en realizar una predicción sobre el tema del texto. Se realiza sin necesidad de leer el texto en sí mismo. Hacemos una predicción basándonos en los elementos resaltados del texto y en el paratexto. 

1.1. Estrategias de Lectura
Skimming: implica una lectura selectiva, ya que consiste en leer solo partes del texto con el objetivo de localizar la(s) idea principal(es).
 Scanning: implica pasar la vista por el texto con una pregunta en mente o con un propósito, por ejemplo, buscar información específica.

1.2. Cognados o palabras transparentes: son aquellas palabras de dos lenguas diferentes que poseen un origen común, ortografía y pronunciación similar y sinonimia cercana.

1.3. Falsos cognados o Falsos amigos:Los falsos cognados o falsos amigos que son palabras que se escriben igual o muy parecido en ambos idiomas -castellano e inglés- pero que, por el contrario, difieren ampliamente en su significado.

3. Verbo "To be"
Sus significados principales son los siguientes: Ser o Estar
Sirve para expresar la edad y también sensaciones, en cuyo caso se traduce como ‘tener’.
Otro caso particular es cuando se habla del clima y entonces se traducirá como “hacer”.
Existen otros casos donde el verbo TO BE se emplea como auxiliar para conjugar tiempos verbales y también para dar órdenes de manera impersonal.

2.1. Formas Affirmativa, Negativa, Interrogativa
![TRES](https://user-images.githubusercontent.com/87509699/176022610-6c4e5429-f8b5-49e1-8e46-5a2cf0f3feea.jpg)


4. Presente Simple
Podemos emplear el presente simple para:

-  referirnos a cosas que siempre son verdad, o que consideramos como hechos,
- para hablar de nuestros hábitos: para aportar más información sobre las rutinas podemos añadir adverbios de frecuencia, como **always, sometimes, hardly ever, never** .
- también puede hacer alusión al futuro en algunas ocasiones: detrás de algunos adverbios o locuciones adverbiales de futuro, como **when, before, after, as soon as, until** , usamos asimismo el presente simple, aunque estemos refiriéndonos al futuro

3.1. Auxiliares y reglas
Los auxiliares que se usan son DO y DOES para la forma interrogativa y negativa.
![10b-3-presente-simple-en-ingles](https://user-images.githubusercontent.com/87509699/176023901-c337216f-a199-47b1-a4e1-16d5ce4d6e7f.jpg)

3.2. Excepciones y variantes

- Si el verbo termina en una vocal que no sea “e”, se añade “-es” en la tercera persona del singular,
- También añadimos “-es” si el verbo termina en una de las siguientes consonantes: s, z, ch, sh o x.
- Si el verbo termina en una consonante seguida de “y”, es necesario cambiar la “y” por una “i” para, después, seguir la regla anterior añadiendo “-es”

4. Términos gramaticales
<html>
<body>


Término | Definición | Ej. en castellano | Ejemplo en inglés
-- | -- | -- | --
Adjetivo | palabra que se agrega al sustantivo para designar una cualidad o determinar su extensiónModifica al sustantivo | ImportanteBuenoÚtil | importantgoodusefulNo tienen género o número, es decir que no hay diferencias entre femenino/masculino singular/plural
Adverbio | Modifica el verbo, el adjetivo u otro adverbio. | muybiendelicadamente | verywelldelicately
Artículos | Preceden a los sustantivos | el – la –los –lasun - unaunos - unas | thea – an--
Conectores | Palabras o frases que unen | yperopara que | andbutso that
Preposiciones | Palabras o frases que unen | deendelante de | ofinin front of
Pronombres | Reemplazan al sustantivo | ellosmíole | theyminehim
Sustantivo | Palabra que designa un ser, objeto o lugar | alumnopublicaciónodontologíaaula | studentpublicationdentistryclassroom
Verbo | Palabra que designa acciones (por extensión, palabras como “estar” o “parecer” son considerados verbos, aunque no denotan una acción) | leeraprenderserestarpareceraumentar | readlearnbebeseem/appearincrease

<br class="Apple-interchange-newline">
</body>
</html>

4.1. Palabras estructurales - Palabras conceptuales

Palabras conceptuales o de contenido (expresan conceptos; transmiten significado): sustantivos, verbos, adjetivos y adverbios. 

Palabras estructurales (ayudan a darle una estructura coherente y cohesiva al texto): preposiciones, artículos, conjunciones y pronombres.


4.2. Adverbios de frecuencia
![adverbs-frequency](https://user-images.githubusercontent.com/87509699/176023374-655d7384-587d-45f6-801e-47c3d9b41a05.jpeg)
